sudo: false

language: node_js

# os:
#   - linux
#   - osx
#   - windows

node_js:
  # - 6
  # - 7
  # - 8
  - lts/*

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn lint
  - yarn build
